<div class="max-w-xl mx-auto flex justify-between items-center sm:flex-row flex-col">
	<figure>
		<table>
			<tr>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>C</td>
			</tr>
			<tr>
				<td>4</td>
				<td>5</td>
				<td>6</td>
				<td>D</td>
			</tr>
			<tr>
				<td>7</td>
				<td>8</td>
				<td>9</td>
				<td>E</td>
			</tr>
			<tr>
				<td>A</td>
				<td>0</td>
				<td>B</td>
				<td>F</td>
			</tr>
		</table>
		<figcaption class="my-2">COSMAC VIP keypad</figcaption>
	</figure>

	<figure>
		<table>
			<tr>
				<td>1</td>
				<td>2</td>
				<td>3</td>
				<td>4</td>
			</tr>
			<tr>
				<td>Q</td>
				<td>W</td>
				<td>E</td>
				<td>R</td>
			</tr>
			<tr>
				<td>A</td>
				<td>S</td>
				<td>D</td>
				<td>F</td>
			</tr>
			<tr>
				<td>Z</td>
				<td>X</td>
				<td>C</td>
				<td>V</td>
			</tr>
		</table>
		<figcaption class="my-2">QWERTY equivalent</figcaption>
	</figure>
</div>
